# Generated by Django 4.1.1 on 2022-09-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='Eye',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
    ]
